import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-port-terminal-handling-invoice-audit",
  "engine": "recovery",
  "title": "Port Terminal Handling Invoice Audit",
  "shortTitle": "Port Terminal Handling Invoice Audit",
  "tagline": "Audit marine terminal handling and service charges using tariff, equipment, cargo, and event evidence.",
  "industry": "Port Cost Recovery",
  "buyer": "Ocean shippers, NVOCCs, and cargo owners",
  "uiPort": 4699,
  "apiPort": 5699,
  "accent": "#c2410c",
  "currency": "USD",
  "primaryOutcome": "Port Terminal Handling Invoice Audit converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect terminal tariffs, bookings, containers, gate moves, lifts, wharfage, security, reefer power, examinations, invoices, and credits in one accountable workflow. Audit marine terminal handling and service charges using tariff, equipment, cargo, and event evidence.",
  "calculation": {
    "actualKey": "chargedAmount",
    "expectedKey": "supportedAmount",
    "actualLabel": "Charged or Paid Amount",
    "expectedLabel": "Evidence-Supported Amount",
    "varianceLabel": "Potential recovery or avoided cost",
    "direction": "actual-minus-expected",
    "finding": "Port Terminal Handling Invoice Audit evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective agreement, eligibility rules, and accountable parties",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare the correction, recovery, or compliance package",
      "Track counterparty response, approval, cash, and preventive control closure"
    ]
  }
},[
feature("terminal-tariff-library","PTH01","Terminal tariff library","Execute terminal tariff library using terminal tariffs, bookings, containers, gate moves, lifts, wharfage, security, reefer power, examinations, invoices, and credits.","Produce a governed terminal tariff library decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Terminal / Shipment Call","text","Terminal / Shipment Call · Standard Case"],["caseReference","Terminal tariff library Reference","text","PTH01-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1277500],["supportedAmount","Evidence-Supported Amount","currency",1073100],["domainDriver","Terminal Charge","select","Handling",["Handling","Wharfage","Reefer power"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Terminal tariff library case","Booking container registry case","Gate event ingestion case","Lift move validation case","Wharfage calculation case"]}),
feature("booking-container-registry","PTH02","Booking container registry","Execute booking container registry using terminal tariffs, bookings, containers, gate moves, lifts, wharfage, security, reefer power, examinations, invoices, and credits.","Produce a governed booking container registry decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Terminal / Shipment Call","text","Terminal / Shipment Call · Standard Case"],["caseReference","Booking container registry Reference","text","PTH02-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1277500],["supportedAmount","Evidence-Supported Amount","currency",1073100],["domainDriver","Terminal Charge","select","Handling",["Handling","Wharfage","Reefer power"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Terminal tariff library case","Booking container registry case","Gate event ingestion case","Lift move validation case","Wharfage calculation case"]}),
feature("gate-event-ingestion","PTH03","Gate event ingestion","Execute gate event ingestion using terminal tariffs, bookings, containers, gate moves, lifts, wharfage, security, reefer power, examinations, invoices, and credits.","Produce a governed gate event ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Terminal / Shipment Call","text","Terminal / Shipment Call · Standard Case"],["caseReference","Gate event ingestion Reference","text","PTH03-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1277500],["supportedAmount","Evidence-Supported Amount","currency",1073100],["domainDriver","Terminal Charge","select","Handling",["Handling","Wharfage","Reefer power"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Terminal tariff library case","Booking container registry case","Gate event ingestion case","Lift move validation case","Wharfage calculation case"]}),
feature("lift-move-validation","PTH04","Lift move validation","Execute lift move validation using terminal tariffs, bookings, containers, gate moves, lifts, wharfage, security, reefer power, examinations, invoices, and credits.","Produce a governed lift move validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Terminal / Shipment Call","text","Terminal / Shipment Call · Standard Case"],["caseReference","Lift move validation Reference","text","PTH04-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1277500],["supportedAmount","Evidence-Supported Amount","currency",1073100],["domainDriver","Terminal Charge","select","Handling",["Handling","Wharfage","Reefer power"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Terminal tariff library case","Booking container registry case","Gate event ingestion case","Lift move validation case","Wharfage calculation case"]}),
feature("wharfage-calculation","PTH05","Wharfage calculation","Execute wharfage calculation using terminal tariffs, bookings, containers, gate moves, lifts, wharfage, security, reefer power, examinations, invoices, and credits.","Produce a governed wharfage calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Terminal / Shipment Call","text","Terminal / Shipment Call · Standard Case"],["caseReference","Wharfage calculation Reference","text","PTH05-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1277500],["supportedAmount","Evidence-Supported Amount","currency",1073100],["domainDriver","Terminal Charge","select","Handling",["Handling","Wharfage","Reefer power"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Terminal tariff library case","Booking container registry case","Gate event ingestion case","Lift move validation case","Wharfage calculation case"]}),
feature("security-fee-audit","PTH06","Security fee audit","Execute security fee audit using terminal tariffs, bookings, containers, gate moves, lifts, wharfage, security, reefer power, examinations, invoices, and credits.","Produce a governed security fee audit decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Terminal / Shipment Call","text","Terminal / Shipment Call · Standard Case"],["caseReference","Security fee audit Reference","text","PTH06-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1277500],["supportedAmount","Evidence-Supported Amount","currency",1073100],["domainDriver","Terminal Charge","select","Handling",["Handling","Wharfage","Reefer power"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Terminal tariff library case","Booking container registry case","Gate event ingestion case","Lift move validation case","Wharfage calculation case"]}),
feature("reefer-power-duration","PTH07","Reefer power duration","Execute reefer power duration using terminal tariffs, bookings, containers, gate moves, lifts, wharfage, security, reefer power, examinations, invoices, and credits.","Produce a governed reefer power duration decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Terminal / Shipment Call","text","Terminal / Shipment Call · Standard Case"],["caseReference","Reefer power duration Reference","text","PTH07-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1277500],["supportedAmount","Evidence-Supported Amount","currency",1073100],["domainDriver","Terminal Charge","select","Handling",["Handling","Wharfage","Reefer power"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Terminal tariff library case","Booking container registry case","Gate event ingestion case","Lift move validation case","Wharfage calculation case"]}),
feature("hazardous-cargo-fee","PTH08","Hazardous cargo fee","Execute hazardous cargo fee using terminal tariffs, bookings, containers, gate moves, lifts, wharfage, security, reefer power, examinations, invoices, and credits.","Produce a governed hazardous cargo fee decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Terminal / Shipment Call","text","Terminal / Shipment Call · Standard Case"],["caseReference","Hazardous cargo fee Reference","text","PTH08-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1277500],["supportedAmount","Evidence-Supported Amount","currency",1073100],["domainDriver","Terminal Charge","select","Handling",["Handling","Wharfage","Reefer power"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Terminal tariff library case","Booking container registry case","Gate event ingestion case","Lift move validation case","Wharfage calculation case"]}),
feature("overweight-handling","PTH09","Overweight handling","Execute overweight handling using terminal tariffs, bookings, containers, gate moves, lifts, wharfage, security, reefer power, examinations, invoices, and credits.","Produce a governed overweight handling decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Terminal / Shipment Call","text","Terminal / Shipment Call · Standard Case"],["caseReference","Overweight handling Reference","text","PTH09-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1277500],["supportedAmount","Evidence-Supported Amount","currency",1073100],["domainDriver","Terminal Charge","select","Handling",["Handling","Wharfage","Reefer power"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Terminal tariff library case","Booking container registry case","Gate event ingestion case","Lift move validation case","Wharfage calculation case"]}),
feature("customs-exam-charge","PTH10","Customs exam charge","Execute customs exam charge using terminal tariffs, bookings, containers, gate moves, lifts, wharfage, security, reefer power, examinations, invoices, and credits.","Produce a governed customs exam charge decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Terminal / Shipment Call","text","Terminal / Shipment Call · Standard Case"],["caseReference","Customs exam charge Reference","text","PTH10-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1277500],["supportedAmount","Evidence-Supported Amount","currency",1073100],["domainDriver","Terminal Charge","select","Handling",["Handling","Wharfage","Reefer power"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Terminal tariff library case","Booking container registry case","Gate event ingestion case","Lift move validation case","Wharfage calculation case"]}),
feature("empty-return-treatment","PTH11","Empty return treatment","Execute empty return treatment using terminal tariffs, bookings, containers, gate moves, lifts, wharfage, security, reefer power, examinations, invoices, and credits.","Produce a governed empty return treatment decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Terminal / Shipment Call","text","Terminal / Shipment Call · Standard Case"],["caseReference","Empty return treatment Reference","text","PTH11-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1277500],["supportedAmount","Evidence-Supported Amount","currency",1073100],["domainDriver","Terminal Charge","select","Handling",["Handling","Wharfage","Reefer power"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Terminal tariff library case","Booking container registry case","Gate event ingestion case","Lift move validation case","Wharfage calculation case"]}),
feature("invoice-matching","PTH12","Invoice matching","Execute invoice matching using terminal tariffs, bookings, containers, gate moves, lifts, wharfage, security, reefer power, examinations, invoices, and credits.","Produce a governed invoice matching decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Terminal / Shipment Call","text","Terminal / Shipment Call · Standard Case"],["caseReference","Invoice matching Reference","text","PTH12-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1277500],["supportedAmount","Evidence-Supported Amount","currency",1073100],["domainDriver","Terminal Charge","select","Handling",["Handling","Wharfage","Reefer power"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Terminal tariff library case","Booking container registry case","Gate event ingestion case","Lift move validation case","Wharfage calculation case"]}),
feature("terminal-dispute-workflow","PTH13","Terminal dispute workflow","Execute terminal dispute workflow using terminal tariffs, bookings, containers, gate moves, lifts, wharfage, security, reefer power, examinations, invoices, and credits.","Produce a governed terminal dispute workflow decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Terminal / Shipment Call","text","Terminal / Shipment Call · Standard Case"],["caseReference","Terminal dispute workflow Reference","text","PTH13-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1277500],["supportedAmount","Evidence-Supported Amount","currency",1073100],["domainDriver","Terminal Charge","select","Handling",["Handling","Wharfage","Reefer power"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Terminal tariff library case","Booking container registry case","Gate event ingestion case","Lift move validation case","Wharfage calculation case"]}),
feature("credit-reconciliation","PTH14","Credit reconciliation","Execute credit reconciliation using terminal tariffs, bookings, containers, gate moves, lifts, wharfage, security, reefer power, examinations, invoices, and credits.","Produce a governed credit reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Terminal / Shipment Call","text","Terminal / Shipment Call · Standard Case"],["caseReference","Credit reconciliation Reference","text","PTH14-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1277500],["supportedAmount","Evidence-Supported Amount","currency",1073100],["domainDriver","Terminal Charge","select","Handling",["Handling","Wharfage","Reefer power"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Terminal tariff library case","Booking container registry case","Gate event ingestion case","Lift move validation case","Wharfage calculation case"]}),
feature("port-charge-analytics","PTH15","Port charge analytics","Execute port charge analytics using terminal tariffs, bookings, containers, gate moves, lifts, wharfage, security, reefer power, examinations, invoices, and credits.","Produce a governed port charge analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Terminal / Shipment Call","text","Terminal / Shipment Call · Standard Case"],["caseReference","Port charge analytics Reference","text","PTH15-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1277500],["supportedAmount","Evidence-Supported Amount","currency",1073100],["domainDriver","Terminal Charge","select","Handling",["Handling","Wharfage","Reefer power"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Terminal tariff library case","Booking container registry case","Gate event ingestion case","Lift move validation case","Wharfage calculation case"]})
]);
